// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anhcgzmtuywhlgudukho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuaGNnem10dXl3aGxndWR1a2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzQ5NDMsImV4cCI6MjA3MjIxMDk0M30.eeTeso8YuuHHiKhQnueOhOuJw7MPh-pZAqeEmCLACLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});